version: "3.8"

services:
  web:
    build: .
    command: gunicorn invoice_generator.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./invoice_generator/:/usr/src/invoice_generator/
      - static:/usr/src/invoice_generator/static
    expose:
      - 8000
    env_file:
      - ./invoice_generator/invoice_generator/.env
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1347aloalo 
      - POSTGRES_DB=test_bd_dev

  nginx:
    build: ./nginx
    volumes:
      - static:/usr/src/invoice_generator/static
    ports:
      - 1337:80
    depends_on:
      - web

  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: "listen --api-key sk_test_51M7GQJA6JPqo7WNX27cxsEd0t1X1uOa1fWEhd0IszzEbyIxzDORn9xlsSBvbyN3esrsLFyNfIkNs6opaoRxrVW9r00jx3r9FVy --device-name test_stripe_server --forward-to web:8000/webhooks/stripe/"
    env_file:
      - ./invoice_generator/invoice_generator/.env

volumes:
  postgres_data:
  static: