version: "3.8"

services:
  web:
    build: .
    command: gunicorn invoice_generator.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./invoice_generator/:/usr/src/invoice_generator/
      - static:/usr/src/invoice_generator/static
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD} 
      - POSTGRES_DB=${SQL_DATABASE}

  nginx:
    build: ./nginx
    volumes:
      - static:/usr/src/invoice_generator/static
    ports:
      - 1337:80
    depends_on:
      - web

  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: "listen --api-key ${STRIPE_SECRET_KEY} --device-name ${STRIPE_DEVICE_NAME} --forward-to web:8000/webhooks/stripe/"
    env_file:
      - ./.env
volumes:
  postgres_data:
  static: