# Generated by Django 4.1.3 on 2022-11-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0002_alter_item_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item",
                    models.ManyToManyField(to="invoice.item", verbose_name="Item"),
                ),
            ],
            options={"verbose_name": "Order", "verbose_name_plural": "Order",},
        ),
    ]
