# Generated by Django 4.1.3 on 2022-11-25 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0003_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.FloatField()),
            ],
            options={"verbose_name": "Discount", "verbose_name_plural": "Discount",},
        ),
        migrations.CreateModel(
            name="Tax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate", models.FloatField()),
                ("stripe_id", models.CharField(max_length=100, unique=True)),
            ],
            options={"verbose_name": "Tax", "verbose_name_plural": "Tax",},
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name="order",
            name="discount",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="invoice.discount",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tax",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="invoice.tax",
            ),
        ),
    ]
