# Generated by Django 4.1.3 on 2022-11-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_order_order_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='coupon_id',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
