# Generated by Django 4.1.3 on 2022-11-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_alter_discount_coupon_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_quantity',
            field=models.JSONField(default=list),
        ),
    ]
