# Generated by Django 4.1.3 on 2022-11-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_remove_order_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(default='usd', max_length=100),
        ),
    ]
